spring.application.name=projetoweb

# URL de conexão com o banco MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/nome_banco_dados
# Usuário e senha do MySQL
spring.datasource.username=nome_usuario
spring.datasource.password=senha
#Configuração do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect